### ISSUE TITLE
support async in vim

### ISSUE THREAD

**Issue by prabirshrestha** [mhinz/vim-grepper#48] opened 2016-05-18 23:27 UTC
Vim now supports async jobs.

Here is an example on using it. https://github.com/prabirshrestha/async.vim

**Comment by mhinz** [comment] 2016-06-01 19:41
I'll look into it!

**Comment by mhinz** [comment] 2016-06-29 16:06
This is blocked by Vim's implementation of callbacks at the moment.

`:h job-exit_cb`: `Vim checks about every 10 seconds for jobs that ended.`

I've got a working version, but the delay renders it useless at the moment. I hope this will get fixed by upstream in the future.

**Comment by chrisbra** [comment] 2016-06-29 17:02
I don't really know much about the async interface. If the 10 seconds delay is a problem, I would raise my voice on vim_dev. Bram seems to care about such issues currently, so chances are high, it will get fixed soon.

**Comment by mhinz** [comment] 2016-06-29 20:45
@chrisbra Simply replacing `exit_cb` by `close_cb` did the trick. Not sure why the polling is needed for the former, but it works as intended now. Sorry. :)

**Closed** 2016-06-29 21:19 UTC
Labels: enhancement

**Comment by mhinz** [comment] 2016-06-29 21:22
@prabirshrestha It's working now.

Since implementing all the async features was done in a long series of patches, it's hard to say since when the feature is working. Currently it automatically uses async beginning with `7.4.1967` (today's patch level).
