### ISSUE TITLE
Multiline quickfix items

### ISSUE THREAD

**Issue by purpleP** [mhinz/vim-grepper#61] opened 2016-08-11 19:39 UTC
When I've used ag.vim I've used to multiline quickfix items, because with plugin, that makes quickfix editable, it gave me ability to do project wide search and replace easily without worrying to much about how good my regex is (because I could've used regex to search for something and then macros or `cgn` to actually replace what I need).
Then I've started to use this plugin and noticed that quickfix items always contain one line only. I've search for it and found that it's supposedly hard to display multiline quckfix items. But then ag.vim somehow have done that. I've searched through the code of ag.vim and haven't found anything unusual about how they treat quickfix menu.

Could you add this to your plugin?

**Comment by mhinz** [comment] 2016-08-14 10:27
If you say "multiline quickfix item", do you mean one entry displayed over multiple lines (`:set wrap` in the quickfix window) or entries as results of patterns that span multiple lines (like `ag "foo\nbar"`)?

Could you give a small text file as example and the query you're using?

**Comment by purpleP** [comment] 2016-08-14 10:31
Example is simple. 
pattern `'something\notherthing'`
file for example

```
foo
something
otherthing
```
AFAIK vim-grepper would have only `something' in quickfix.

**Comment by mhinz** [comment] 2016-08-14 10:32
Yea, I see what you mean:

```
$ ag 'foo\nbar' test.txt
1:foo
2:bar
$ ag --vimgrep 'foo\nbar' test.txt
test.txt:2:0:bar
```

I'll have a look at ag.vim.

**Comment by mhinz** [comment] 2016-08-14 10:36
Using your example, ag.vim only shows "otherthing" for me as well. Does it show something else for you?

**Comment by purpleP** [comment] 2016-08-14 10:59
@mhinz hm... strange. I've removed vim-grepper, reinstalled ag.nvim and it indeed gives the same result. I would still like to have this feature.

**Comment by mhinz** [comment] 2016-08-14 13:46
Well, I could default to `ag --column --noheading` instead of `ag --vimgrep`. With the former and `'foo\nbar'` as  a query, you'd get both "foo" and "bar, but it will still be 2 different entries in the quickfix list.

Other than that there's not much I can do.

**Comment by mhinz** [comment] 2016-08-18 14:35
I played around with a few ideas, but this is something that needs to be fixed in ag. Closing.

**Closed by mhinz** 2016-08-18 14:35 UTC

**Comment by purpleP** [comment] 2016-08-18 18:47
@mhinz Isn't problem in vim, because it couldn't show more than one line in quickfix list? How is this ag problem?

**Comment by mhinz** [comment] 2016-08-18 19:29
I hope I didn't misunderstand the issue here, but I thought the problem is that `ag --vimgrep 'foo\nbar'` is only reporting the "bar" line, so only that line will appear in the quickfix list.

**Comment by purpleP** [comment] 2016-08-19 04:00
Okay, I've digged a little deeper. There are multiple problems.
First - yes, ag `--vimgrep` doesn't display `foo` for some reason and it probably should be fixed in ag.
Second - even without `--vimgrep` option if there are multiple multiline results in the same file there is no way to distinguish them.
For example
`ag 'foo\nbar'` in
```
foo
bar

foo
bar
```
```
t1.txt
1:foo
2:bar
5:foo
6:bar
```

When using ag by hand I haven't thought of that because I've been using `--context` option usually.
