### ISSUE TITLE
Limit number of matches

### ISSUE THREAD

**Issue by yevhen-m** [mhinz/vim-grepper#101] opened 2017-02-22 14:08 UTC
I use `Grepper` with `Ag` to search through my project. When I search for a common string, say `user`, I get too many results. My neovim hammers cpu (100% and does not relax at all, I have to quit), location list (I use it instead of quickfix list) does not open with results, and when I exit vim, it throws an error:
```
Error detected while processing function <SNR>127_on_event:
line    2:
E475: Invalid argument: Channel doesn't existFound 14713 matches.
```
`Ag` handles this search fine by itself, so I suppose that the cause of the problem is getting the results from ag to neovim. 

Is it possible to limit fetched results and say throw an error in case there too many matches? What do you think? 

`NVIM 0.2.0`

My Grepper settings:
```
" Grepper settings {{{
let g:grepper = {}
let g:grepper.highlight = 1
let g:grepper.tools = ['ag']
let g:grepper.prompt = 0
" Use location list
let g:grepper.open = 0
let g:grepper.quickfix = 0

" Open loclist window automatically
autocmd User Grepper lopen
" Search in hidden files
runtime autoload/grepper.vim
let g:grepper.ag.grepprg .= " --hidden"

nnoremap <leader>gr :Grepper -query<space>
nmap gr  <plug>(GrepperOperator)
xmap gr  <plug>(GrepperOperator)
" }}}
```

**Comment by mhinz** [comment] 2017-02-22 14:34
I'd rather add a `:GrepperStop` command in case there's a long-running process without any matches. Is that that fine as well?

I can see how limiting matches is slightly more convienient for a case that shouldn't happen too often in the first place. And then we would still need a way to stop the current search anyway. So I'd like to go with that as the only solution.

BTW, the `on_event` function is not from Grepper.

**Comment by yevhen-m** [comment] 2017-02-22 14:47
`:GrepperStop` is fine. Can it be triggered when say number of matches exceeds X?

**Comment by mhinz** [comment] 2017-02-22 15:47
I played around with some code and the thing is.. `jobstop()` (Neovim) is slow. `job_stop()` (Vim) is even slower.

When I used `:Grepper -tool grep -query a` in `~` with Neovim, then I'd get over 50k matches. With `:Grepper -tool grep -stop 1 -query a` I _should_ get only 1 match, but get around 2k nevertheless. 

I think it would be even worse with Vim.

Considering that, I'm not sure if it makes any sense to provide a number to `-stop`.

**Comment by mhinz** [comment] 2017-02-22 16:05
You can test it yourself:

```
$ git pull && git checkout stop
```

Then just do `:Grepper -tool grep -stop 1 -query a`.

It will take quite long until it stops for Vim and Neovim. With Neovim we even have the problem that libuv caches results and provides multiple lines at once to Neovim.. this means even if there were 2 matches already, Neovim would still think it's 0, because libuv didn't send the data yet. This is an optimization which makes navigating quite more enjoyable if a CPU-bound process runs async opposed to Vim where the whole editor gets sluggish.

**Comment by yevhen-m** [comment] 2017-02-22 17:39
Thanks a lot for the details. I hope there is a solution to this problem, bc it's very sad that you have to restart vim in case there are too many matches (I have to restart it bc it becomes almost unresponsive).

**Comment by mhinz** [comment] 2017-02-23 02:59
So, I improved the stop handling quite a bit now!

```
:Grepper -stop
```
This stops the currently running search.

```
:Grepper -stop 100
```
The starts a search limited to 100. For Vim, that's _exactly_ 100 matches. For Neovim, due to the optimization mentioned above, it can be less or more, but should be around 100 as well.

The default stop size is set to 1000. (Do you consider this is sane value? I'm up for suggestions.)

Anyway, please check this out if it works as expected:

```
$ git pull && git checkout stop
```

**Comment by mhinz** [comment] 2017-02-23 16:40
I merged this into master now. Please update and see `:h :Grepper-stop`.

Thanks for bringing this up!

**Closed by mhinz** 2017-02-23 16:40 UTC
Labels: feature request, feedback-needed

**Comment by yevhen-m** [comment] 2017-02-23 20:11
Thanks a lot for you help!

**Comment by yevhen-m** [comment] 2017-03-03 08:09
Hi, something is going wrong with `Grepper` since  this change.

```
" Grepper settings {{{
let g:grepper = {}
let g:grepper.highlight = 1
let g:grepper.tools = ['ag']
let g:grepper.prompt = 0
let g:grepper.stop = 10000
" Use location list
let g:grepper.open = 0
let g:grepper.quickfix = 0

" Open quickfix window automatically
autocmd User Grepper lopen
" Search in hidden fields with ag
runtime autoload/grepper.vim
let g:grepper.ag.grepprg .= " --hidden"


nnoremap <leader>gr :Grepper -query<space>
nmap gr  <plug>(GrepperOperator)
xmap gr  <plug>(GrepperOperator)
" }}}
```
When I start searching, vim is hammering the cpu and memory footprint is growing constantly. But when I execute `:Grepper-stop`, searching stops and I get all the matches. In my case 212 matches, and I suppose it's too little to bother vim. So apparently something is going wrong.
Could you investigate this issue?

**Comment by mhinz** [comment] 2017-03-03 11:36
Well, I have no issues here. If you're using Vim, there's not even a temporary buffer used. Every line gets put into the qf/loc list immediately.

`ag --hidden` on a huge directory will of course take some time. Even more when using Vim as the middleman. And if you then search something generic as "a", ag will output loads of lines, which makes it even harder for Vim to process everything.

Since I can't reproduce it, you have to find out which commit introduced the problem. Try these in this order:

- `df7e310`
- `3a89dd4` (although this commit was never meant to be used directly)
- `d5bcb4a`

What was the exactly query used? Vim or Neovim?

**Comment by yevhen-m** [comment] 2017-03-03 11:51
@mhinz thanks, I'll try to disable `--hidden` flag. Hope that's the cause.

**Comment by yevhen-m** [comment] 2017-03-04 15:09
It seems that you were right, searching without `--hidden` flag works as expected. Thanks!
