### ISSUE TITLE
Grepper{Ack,Pt,Rg} are async in Neovim, but not Vim

### ISSUE THREAD

**Issue by habamax** [mhinz/vim-grepper#65] opened 2016-09-26 20:04 UTC
vim8 and windows 10

pt is installed.

Trying to 

```
:GrepperPt something<CR>
```

returns nothing although there is 'something' in the file.

Next thing is: 

```
:GrepperPt<CR>

Error detected while processing function <SNR>77_on_exit:
line 10
E108: No such variable: "s:id"
```

**Comment by mhinz** [comment] 2016-09-26 20:10
Unfortunately I can't test for Windows. Is `rg --no-column --vimgrep -i something` working manually?

**Comment by habamax** [comment] 2016-09-26 20:18
yep

    pt --nogroup something

gives a lot of results  in a console

**Comment by mhinz** [comment] 2016-09-26 20:20
Could you paste the output? I wonder if it's a different format than the expected one. It should look like this:

```
file1:12: there is something
file2:99: something rocks
```

**Comment by habamax** [comment] 2016-09-26 20:26
tables.html:412:<td style="text-align: left;">12 (something to do with Clinton and maybe the '60's)</td>
    tables.md:188:            (here's            (due to           (something to do
    tables.tex:403:12 (something to do with Clinton and maybe the '60's)\strut

![grepper](https://cloud.githubusercontent.com/assets/234774/18850507/8daaf0ca-8440-11e6-9229-83d38785a4b4.png)

**Comment by habamax** [comment] 2016-09-26 20:29
If I issue 

     GrepperPt asdlfkjsdlfkjsldkfjal

I get a message: "No matches found"

Otherwise silence and no results (but they should be)

**Comment by habamax** [comment] 2016-09-26 20:33
GrepperGrep, GrepperFindstr, GrepperGit works, btw

**Comment by mhinz** [comment] 2016-09-26 20:35
Hmm, apparently Vim's async interface changed a bit. I can reproduce it on OSX as well now.

I'm looking into it.

**Comment by habamax** [comment] 2016-09-26 20:35
Ok, thx a lot.

**Comment by mhinz** [comment] 2016-09-27 10:41
Short update:

I'm pretty sure it's a Vim bug by now. Some jobs simply never return. E.g. `:GrepperGrep`, `:GrepperGit`, `:GrepperAg` work, but `:GrepperAck` and `:GrepperRg` don't.

Here a minimal test case: https://gist.github.com/mhinz/a5d126e6c702a6ffd0347aa70c9ccb39
(ag will give output, rg won't.)

It seems to be related to this bug: https://groups.google.com/forum/#!topic/vim_dev/xro9LJ-X6oo

**Comment by mhinz** [comment] 2016-09-27 10:54
@chrisbra Sorry for disturbing you, but could you have a look at the minimal test case in the above post? I read vim_dev a bit, but I'm still not sure if that bug is already reported. Thanks in advance!

(If you don't have `rg` installed, you can use `ack --noheading --column foo` for cmd2 as well.)

**Comment by chrisbra** [comment] 2016-09-27 19:18
Not sure, if this has already been mentioned, there are a couple of bugs mentioned in the [todo list](https://github.com/vim/vim/blob/master/runtime/doc/todo.txt#L52-L74) and in the issue tracker like vim/vim#1026
I'll look into it.

**Comment by chrisbra** [comment] 2016-09-27 20:51
Hm, it looks like ack is still running and waiting for something...

**Comment by mhinz** [comment] 2016-09-27 20:54
Yup, it never returns and the stdout handler is not called even once. I have no idea how async in Vim really works, so I'm rather puzzled by this. :\

**Comment by mgee** [comment] 2016-09-27 21:42
For me `rg` works in async mode (macOS 10.12 + Vim8) if I use `'grepprg': 'rg --no-heading --line-number --column $* .'`
The `.` for the current directory is essential. Otherwise it does not work and it seems rg is waiting for data from stdin.

**Comment by mhinz** [comment] 2016-09-27 21:56
@mgee Hmm, I see.. https://github.com/BurntSushi/ripgrep/issues/19

**Comment by mhinz** [comment] 2016-09-28 13:02
So, when both, Neovim's `jobstart()` and Vim's `job_start()`, use pipes by default, where's the difference?

There must be some smart code in [libuv](https://github.com/libuv/libuv) (which is used by Neovim) that isn't part of Vim's custom solution.

**Comment by chrisbra** [comment] 2016-09-28 15:05
sounds like it. I wonder if there is something, that should be done by Vim.

**Comment by mhinz** [comment] 2016-11-11 14:04
Actually closed by: https://github.com/mhinz/vim-grepper/pull/77

**Closed** 2016-11-11 14:03 UTC
Labels: vim-bug
