### ISSUE TITLE
doesn't return results

### ISSUE THREAD

**Issue by teto** [mhinz/vim-grepper#29] opened 2016-01-26 20:55 UTC
I launch `Grepper -tool ag  -open -switch` in neovim 45b37 (<1 week) and then I launch a search for which I know for sure there are results. The research failed because it is interrupted by an error:

```
ERR: Skipping ./files-0/tmp/socket2: Error opening file: No such device or address

Erreur détectée en traitant function <SNR>96_on_stderr :                                                                                    
ligne    1 :                                                                                                                                
E900: Invalid job id       
```
It happens systematically.

**Comment by mhinz** [comment] 2016-01-26 21:18
Hmm, I can't reproduce it on OSX. 

Where is that `./files-0/tmp/socket2` file? Maybe it's tripped up by the socket file, although I wouldn't know why.

1. Can you verify that line 1 of `s:on_stderr()` in `autoload/grepper.vim` starts with `silent!`?
2. Does it work when you use a query that never matches?
3. Does it work if you change the working directory to a completely different directory?

**Comment by teto** [comment] 2016-01-26 21:27
File got permission: 
srwxrwxr-x 1 teto teto 0 janv.  7 15:32 files-0/tmp/socket2=

I removed the file and it worked again. I have no autoload/grepper.vim. I just ran a PlugUpdate but I can't reproduce since I just deleted the socket and dunno how to recreate one easily (silly me).

**Comment by mhinz** [comment] 2016-01-26 23:36
It's fixed now. Thanks for reporting!

**Closed** 2016-01-26 23:36 UTC

**Comment by teto** [comment] 2016-01-26 23:39
Thanks for fixing this and all your great plugins (I am mattX on neovim's irc ;) )

**Comment by mhinz** [comment] 2016-01-26 23:40
Hah, you're welcome!
