### ISSUE TITLE
Error in s:prompt with <sid>complete_files

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#123] opened 2017-07-13 14:54 UTC
When trying to complete after `:Grepper -tool rg` I am getting an error (after closing/ending) the input():

```
Error detected while processing function <SNR>4_lod_cmd[3]..<SNR>125_parse_flags[74]..<SNR>125_start[6]..<SNR>125_process_flags[35]..<SNR>125_prompt:
line   19:
E117: Unknown function: <sid>complete_files
Error detected while processing function <SNR>4_lod_cmd[3]..<SNR>125_parse_flags[74]..<SNR>125_start[6]..<SNR>125_process_flags:
line   35:
E171: Missing :endif
Error detected while processing function <SNR>4_lod_cmd[3]..<SNR>125_parse_flags[74]..<SNR>125_start:
line    6:
E171: Missing :endif
```

In Neovim it looks like this:
```
Error detected while processing function <SNR>2_lod_cmd[3]..<SNR>177_parse_flags[74]..<SNR>177_start[6]..<SNR>177_process_flags[35]..<SNR>177_prompt:
line   19:                                                                                                                                           
E120: Using <SID> not in a script context: <sid>complete_files
Error detected while processing function <SNR>2_lod_cmd[3]..<SNR>177_parse_flags[74]..<SNR>177_start[6]..<SNR>177_process_flags:
line   35:                                                                                                                      
E171: Missing :endif
Error detected while processing function <SNR>2_lod_cmd[3]..<SNR>177_parse_flags[74]..<SNR>177_start:
line    6:                                                                                           
E171: Missing :endif
```

**Comment by mhinz** [comment] 2017-07-13 15:01
Seems like a config issue? `s:lod_cmd()` belongs to vim-plug.

How do you complete? Can you specify the exact keys you hit?

**Comment by mhinz** [comment] 2017-07-13 16:01
Or do you do any lazy loading magic?

**Comment by blueyed** [comment] 2017-07-13 16:37
I am using vim-plug, yes:

```vim
    Plug 'mhinz/vim-grepper', { 'on': ['Grepper', '<plug>(GrepperOperator)'] }
```

But it also happens when not loading it lazily:
```
Error detected while processing function <SNR>126_parse_flags[74]..<SNR>126_start[6]..<SNR>126_process_flags[35]..<SNR>126_prompt:
line   19:                                                                                                                        
E120: Using <SID> not in a script context: <sid>complete_files
```

But from what I remember it would be better to have the completion function in `autoload` instead, but I also see that you moved stuff out of it?!

**Comment by mhinz** [comment] 2017-07-13 17:35
> you moved stuff out of it?!

Yup, there was no reason for autoloading anymore, since almost everything has to be initialized at the start anyway. But I don't see why script-local functions for completion would be a bad thing.

Although.. I don't get any error, but just `:Grepper -<tab>` is doing nothing instead of completing. Argh.

I'm looking into it.

**Comment by mhinz** [comment] 2017-07-13 17:41
Scratch that, completion is working as expected for me. I was just a victim of my own testing environment (and lazy loading).

I can't reproduce it so far.

Just to be on the safe side, this should reproduce it right?

`:Grepper -tool rg<space><tab>`. This actually thows an error, but you don't see it until you end the prompt. Is that correct?

**Comment by blueyed** [comment] 2017-07-13 19:35
Sorry for the confusing repro.

I am doing `:Grepper -tool rg<cr>`, then on the `input()` (`rg -H --no-heading --vimgrep --sort-files>` (customized)) I type `foo <tab>`.
Nothing completes, but after `Escape` I get the error.

**Comment by mhinz** [comment] 2017-07-13 22:52
Oh, you probably changed the default `g:grepper.next_tool`, eh? Otherwise `<tab>` would change to the next tool instead of trying to complete.

I can reproduce it now.

**Comment by mhinz** [comment] 2017-07-13 22:55
Should be fixed now. 🎉

Thanks for finding this!

**Closed** 2017-07-13 22:54 UTC
