### ISSUE TITLE
Passing a path using -side,  the results buffer is not highlighted & I can't use key mappings 

### ISSUE THREAD

**Issue by ahmedelgabri** [mhinz/vim-grepper#85] opened 2016-12-13 18:48 UTC
I expect the results buffer to be highlighted & that I can still use `n` & `N` etc... to move around. which is not the case right now.

This works fine
```vim
:Grepper -query foo ./path/to/folder
```

This doesn't
```vim
:Grepper -side -query foo ./path/to/folder
```

And here is my poster child example for search for `fzf` 😄 

```vim
:Grepper -side -query fzf ./zsh/
```

This is the result

<img width="1680" alt="screen shot 2016-12-13 at 19 46 27" src="https://cloud.githubusercontent.com/assets/63876/21153926/e06455f4-c16c-11e6-873c-1a5592f83fbb.png">

**Comment by mhinz** [comment] 2016-12-13 19:02
> And here is my poster child example for search for fzf

;-P

I can reproduce it. Will looking into it now.

**Comment by mhinz** [comment] 2016-12-13 19:35
It's more or less a more fundamental issue. :\

The thing is, `-highlight` itself is not perfect and will break (no errors but no highlighting as well) for more complex queries. That's where https://github.com/mhinz/vim-grepper/issues/60 would come in handy.

And now the issue in this case is that your query actually is `fzf ./`, and that can't be highlighted. It could also be `-i 'foo bar' .`. How would you find the actual query in such a string? It's no trivial problem for sure.

Anyway, the real issue is that `normal! n` fails for jumping to the first match. A simple `silent!` before it makes highlighting the files and separators and jumping around via `]]` etc. work again, but you still won't get query highlighting.

**Comment by ahmedelgabri** [comment] 2016-12-14 11:36
Good enough , thanks 😊

One small question if I want to pass flags/args to the underlying tool do I need to do something like `-args flag1 flag2 flagn...` or how can I do this?

**Comment by mhinz** [comment] 2016-12-14 12:10
Multiple ways! Let's assume we wanted to add a simple `-i` to git:

1. They could simply be part of the query. E.g. `-i foo` in the prompt or or `:Grepper -tool git -query -i foo *.c` or `:GrepperGit -i foo`.

2. `:Grepper -tool git -noprompt -grepprg git grep -nIi foo`.

3. In your vimrc:

```vim
runtime autoload/grepper.vim
let g:grepper.git.grepprg .= ' -i'
```

See `:h g:grepper` and `:h grepper-tools`.

**Comment by mhinz** [comment] 2016-12-14 12:42
Closing this, since the problem at hand is fixed. If we ever find a good solution for perfect highlighting, `-side` will instantly become better as well. :-)

Thanks for bringing this up!

(Feel free to ask further questions, if there's anything unclear, though.)

**Closed by mhinz** 2016-12-14 12:42 UTC
Labels: bug, solved?

**Comment by ahmedelgabri** [comment] 2016-12-14 19:23
Will that work if I do stuff like this for example?

```vim
:Grepper -side -tool ag -G="*.js" -l -query foo
```

**Comment by mhinz** [comment] 2016-12-14 19:48
Nope, `-tool` just takes the tool name. You would have to use `-grepprg`, but that doesn't work either, because from all the flags, `-grepprg` and `-query` have to be the last flag (since it's impossible to determine when their input ends), so you can't combine them.

I think the best solution would be to simply add it as a new tool! It might look complicated, but it really easy actually:

```
runtime autoload/grepper.vim
let g:grepper.agjs = copy(g:grepper.ag)
let g:grepper.agjs.grepprg .= ' -G="*.js"'
let g:grepper.tools += ['agvim']
```

Lines explained:

1. Initialize `g:grepper` with all the default values. Afterwards you can access `:echo g:grepper.ag`.
2. We create a new tool called "agjs" by simply copying the "ag" defaults.
3. Add what you want to `grepprg`, which contains the line that gets run in the shell.
4. Add `agjs` to the list of available tools. That will make it available to tab completion on `:Grepper -tool <tab>` and so on.

**Comment by ahmedelgabri** [comment] 2016-12-14 19:53
Nice! thanks very much 👍
